#!/bin/bash

APP_VERSION=${APP_VERSION:-$(< ./VERSION)}
NUMBER_OF_COMMIT=$(git rev-list HEAD --count)
SHA_COMMIT=$(git rev-parse --short HEAD)
BUILD_DATE=$(date +%Y%m%d-%H%M%S)
BUILD_VERSION=$APP_VERSION.$NUMBER_OF_COMMIT-$SHA_COMMIT-$BUILD_DATE

export GOPATH=${PWD}/vendor:${PWD}/vendor/src/github.com/coreos/dex/Godeps/_workspace:${PWD}
export GOBIN=${PWD}/bin

LD_FLAGS="-X main.version=$BUILD_VERSION"

if [ "$1" = "cross" ]; then
    echo "Cross Build for linux and osx"
    env GOOS=linux GOARCH=amd64 gb build -ldflags="$LD_FLAGS" otsimo/dex-worker
    env GOOS=linux GOARCH=amd64 gb build -ldflags="$LD_FLAGS" otsimo/accounts
    env GOOS=linux GOARCH=amd64 gb build -ldflags="$LD_FLAGS" otsimo/dexctl
    env GOOS=linux GOARCH=amd64 gb build -ldflags="$LD_FLAGS" otsimo/dex-overlord

    env GOOS=darwin GOARCH=amd64 gb build -ldflags="$LD_FLAGS" otsimo/dex-worker
    env GOOS=darwin GOARCH=amd64 gb build -ldflags="$LD_FLAGS" otsimo/accounts
    env GOOS=darwin GOARCH=amd64 go build -ldflags="$LD_FLAGS" otsimo/dexctl
    env GOOS=darwin GOARCH=amd64 gb build -ldflags="$LD_FLAGS" otsimo/dex-overlord

elif [ "$1" = "docker" ]; then
    echo "Cross Build for linux amd64"
    env GOOS=linux GOARCH=amd64 gb build -ldflags="$LD_FLAGS" otsimo/dex-worker
    env GOOS=linux GOARCH=amd64 gb build -ldflags="$LD_FLAGS" otsimo/accounts
    env GOOS=linux GOARCH=amd64 gb build --ldflags="$LD_FLAGS" otsimo/dex-overlord
    go build -ldflags="$LD_FLAGS" otsimo/dexctl

else
    echo "Build for" $(go env GOOS)
    gb build -ldflags="$LD_FLAGS" otsimo/dex-worker
    gb build -ldflags="$LD_FLAGS" otsimo/accounts
    gb build -ldflags="$LD_FLAGS" otsimo/dexctl
    gb build -ldflags="$LD_FLAGS" otsimo/dex-overlord
fi

# Rename files

if [ -f ./bin/dex-worker ]; then
   mv ./bin/dex-worker ./bin/dex-worker-$(go env GOOS)-amd64
fi

if [ -f ./bin/dex-overlord ]; then
   mv ./bin/dex-overlord ./bin/dex-overlord-$(go env GOOS)-amd64
fi

if [ -f ./bin/dexctl ]; then
   mv ./bin/dexctl ./bin/dexctl-$(go env GOOS)-amd64
fi

if [ -f ./bin/accounts ]; then
   mv ./bin/accounts ./bin/accounts-$(go env GOOS)-amd64
fi